version: "3.7"
services:
    nginx:
        image: nginx:latest
        container_name: nginx_conoha
        ports:
            - "80:80"
        volumes:
            - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
            - ./nginx/conf:/etc/nginx/conf.d
            - ./front_src:/var/www/html
        # depends_on:
        #     - django
    # django:
    #     build: ./django
    #     container_name: django
    #     expose:
    #         - '8001'
    #     volumes:
    #         - ./src:/code
    #     command: uwsgi --socket :8001 --module mysite.wsgi
    #     depends_on:
    #         - db
    # db:
    #     image: postgres:latest
    #     container_name: db
    #     volumes:
    #         - ./db/dbdata:/var/lib/postgresql/data
    #     expose:
    #         - '5432'
    #     environment:
    #         - POSTGRES_USER=hogehoge
    #         - POSTGRES_PASSWORD=password
    #         - POSTGRES_DB=testDB