version: "3.7"
services:
    nginx:
        image: nginx:latest
        container_name: nginx_conoha
        ports:
        - "80:80"
        volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./src:/var/www/html